export const PERFIS_SISTEMA = {
  ADMINISTRADOR: 'administrador',
  ADMIN_EMPRESA: 'admin_empresa',
  GERENTE: 'gerente',
  ATENDENTE: 'atendente',
  VENDAS: 'vendas',
  RECEBIMENTO: 'recebimento',
  TECNICO: 'tecnico',
  ESTOQUISTA: 'estoquista',
  FINANCEIRO: 'financeiro',
  GARANTIAS: 'garantias',
  FISCAL: 'fiscal',
} as const;

export type PerfilSistema = (typeof PERFIS_SISTEMA)[keyof typeof PERFIS_SISTEMA];

export const EVENTOS_NEGOCIO = {
  EMPRESA_CONSULTAR: 'empresa.consultar',
  EMPRESA_GERENCIAR: 'empresa.gerenciar',
  USUARIO_CONSULTAR: 'usuario.consultar',
  USUARIO_GERENCIAR: 'usuario.gerenciar',

  RECEBIMENTO_CRIAR: 'recebimento.criar',
  RECEBIMENTO_CONSULTAR: 'recebimento.consultar',
  RECEBIMENTO_EDITAR: 'recebimento.editar',
  RECEBIMENTO_GERAR_TERMO: 'recebimento.gerar_termo',
  RECEBIMENTO_REMOVER: 'recebimento.remover',

  CLIENTE_CONSULTAR: 'cliente.consultar',
  CLIENTE_CRIAR: 'cliente.criar',
  CLIENTE_EDITAR: 'cliente.editar',
  CLIENTE_REMOVER: 'cliente.remover',

  CATALOGO_CONSULTAR: 'catalogo.consultar',
  CATALOGO_GERENCIAR: 'catalogo.gerenciar',

  ORCAMENTO_CRIAR: 'orcamento.criar',
  ORCAMENTO_CONSULTAR: 'orcamento.consultar',
  ORCAMENTO_EDITAR_RASCUNHO: 'orcamento.editar_rascunho',
  ORCAMENTO_ENVIAR: 'orcamento.enviar',
  ORCAMENTO_APROVAR: 'orcamento.aprovar',
  ORCAMENTO_REPROVAR: 'orcamento.reprovar',
  ORCAMENTO_CANCELAR: 'orcamento.cancelar',

  OS_CRIAR: 'os.criar',
  OS_CONSULTAR: 'os.consultar',
  OS_INICIAR_DIAGNOSTICO: 'os.iniciar_diagnostico',
  OS_AGUARDAR_PECA: 'os.aguardar_peca',
  OS_RESERVAR_PECA: 'os.reservar_peca',
  OS_INICIAR_EXECUCAO: 'os.iniciar_execucao',
  OS_CONSUMIR_PECA: 'os.consumir_peca',
  OS_FINALIZAR: 'os.finalizar',
  OS_CANCELAR: 'os.cancelar',

  ESTOQUE_CONSULTAR: 'estoque.consultar',
  ESTOQUE_ENTRADA: 'estoque.entrada',
  ESTOQUE_RESERVAR: 'estoque.reservar',
  ESTOQUE_BAIXAR: 'estoque.baixar',
  ESTOQUE_AJUSTAR: 'estoque.ajustar',
  ESTOQUE_ESTORNAR: 'estoque.estornar',

  FORNECEDOR_CONSULTAR: 'fornecedor.consultar',
  FORNECEDOR_GERENCIAR: 'fornecedor.gerenciar',
  COMPRA_PEDIDO_CONSULTAR: 'compra_pedido.consultar',
  COMPRA_PEDIDO_GERENCIAR: 'compra_pedido.gerenciar',

  VENDA_CONSULTAR: 'venda.consultar',
  VENDA_GERAR: 'venda.gerar',
  VENDA_CANCELAR: 'venda.cancelar',
  PAGAMENTO_CONSULTAR: 'pagamento.consultar',
  PAGAMENTO_REGISTRAR: 'pagamento.registrar',
  PAGAMENTO_ESTORNAR: 'pagamento.estornar',

  LIVRO_CAIXA_CONSULTAR: 'livro_caixa.consultar',
  CONTA_FINANCEIRA_CONSULTAR: 'conta_financeira.consultar',
  CONTA_FINANCEIRA_GERENCIAR: 'conta_financeira.gerenciar',
  CATEGORIA_FINANCEIRA_CONSULTAR: 'categoria_financeira.consultar',
  CATEGORIA_FINANCEIRA_GERENCIAR: 'categoria_financeira.gerenciar',
  TITULO_FINANCEIRO_CONSULTAR: 'titulo_financeiro.consultar',
  TITULO_FINANCEIRO_GERENCIAR: 'titulo_financeiro.gerenciar',
  TITULO_FINANCEIRO_BAIXAR: 'titulo_financeiro.baixar',
  TITULO_FINANCEIRO_ESTORNAR: 'titulo_financeiro.estornar',
  MOVIMENTO_CAIXA_REGISTRAR: 'movimento_caixa.registrar',
  MOVIMENTO_CAIXA_ESTORNAR: 'movimento_caixa.estornar',
  RECORRENCIA_FINANCEIRA_CONSULTAR: 'recorrencia_financeira.consultar',
  RECORRENCIA_FINANCEIRA_GERENCIAR: 'recorrencia_financeira.gerenciar',
  RECORRENCIA_FINANCEIRA_PROCESSAR: 'recorrencia_financeira.processar',
  PROLABORE_REGISTRAR: 'prolabore.registrar',
  FECHAMENTO_MENSAL_GERENCIAR: 'fechamento_mensal.gerenciar',
  RELATORIO_FINANCEIRO_GERAR: 'relatorio_financeiro.gerar',
  ANEXO_FINANCEIRO_CONSULTAR: 'anexo_financeiro.consultar',
  ANEXO_FINANCEIRO_GERENCIAR: 'anexo_financeiro.gerenciar',

  NOTA_FISCAL_CONSULTAR: 'nota_fiscal.consultar',
  NOTA_FISCAL_EMITIR: 'nota_fiscal.emitir',
  NOTA_FISCAL_CANCELAR: 'nota_fiscal.cancelar',

  GARANTIA_ABRIR: 'garantia.abrir',
  GARANTIA_CONSULTAR: 'garantia.consultar',
  GARANTIA_ENVIAR_FORNECEDOR: 'garantia.enviar_fornecedor',
  GARANTIA_REGISTRAR_RETORNO: 'garantia.registrar_retorno',
  GARANTIA_FINALIZAR: 'garantia.finalizar',

  NOTIFICACAO_ENVIAR: 'notificacao.enviar',
  COMUNICACAO_TEMPLATE_GERENCIAR: 'comunicacao_template.gerenciar',
  CONSULTA_IMEI_CONSULTAR: 'consulta_imei.consultar',
  CONSULTA_IMEI_GERENCIAR: 'consulta_imei.gerenciar',

  AUDITORIA_CONSULTAR: 'auditoria.consultar',
  AUDITORIA_GERENCIAR: 'auditoria.gerenciar',
} as const;

export type EventoNegocio = (typeof EVENTOS_NEGOCIO)[keyof typeof EVENTOS_NEGOCIO];

export const PERMISSOES_INTERFACE = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_EMPRESAS: 'MANAGE_EMPRESAS',
  MANAGE_USUARIOS: 'MANAGE_USUARIOS',
  MANAGE_CLIENTES: 'MANAGE_CLIENTES',
  MANAGE_RECEBIMENTOS: 'MANAGE_RECEBIMENTOS',
  MANAGE_ORCAMENTOS: 'MANAGE_ORCAMENTOS',
  MANAGE_ORDENS_SERVICO: 'MANAGE_ORDENS_SERVICO',
  MANAGE_VENDAS: 'MANAGE_VENDAS',
  MANAGE_FINANCEIRO: 'MANAGE_FINANCEIRO',
  MANAGE_GARANTIAS: 'MANAGE_GARANTIAS',
  MANAGE_COMPRAS: 'MANAGE_COMPRAS',
  MANAGE_CATALOGO: 'MANAGE_CATALOGO',
  MANAGE_COMUNICACAO: 'MANAGE_COMUNICACAO',
} as const;

export type PermissaoInterface = (typeof PERMISSOES_INTERFACE)[keyof typeof PERMISSOES_INTERFACE];

export const EVENTOS_POR_PERMISSAO_INTERFACE: Record<PermissaoInterface, readonly EventoNegocio[]> = {
  [PERMISSOES_INTERFACE.VIEW_DASHBOARD]: [
    EVENTOS_NEGOCIO.CLIENTE_CONSULTAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.OS_CONSULTAR,
    EVENTOS_NEGOCIO.VENDA_CONSULTAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_EMPRESAS]: [
    EVENTOS_NEGOCIO.EMPRESA_CONSULTAR,
    EVENTOS_NEGOCIO.EMPRESA_GERENCIAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_USUARIOS]: [
    EVENTOS_NEGOCIO.USUARIO_CONSULTAR,
    EVENTOS_NEGOCIO.USUARIO_GERENCIAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_CLIENTES]: [
    EVENTOS_NEGOCIO.CLIENTE_CONSULTAR,
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_RECEBIMENTOS]: [
    EVENTOS_NEGOCIO.RECEBIMENTO_CRIAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_EDITAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_GERAR_TERMO,
  ],
  [PERMISSOES_INTERFACE.MANAGE_ORCAMENTOS]: [
    EVENTOS_NEGOCIO.ORCAMENTO_CRIAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_EDITAR_RASCUNHO,
    EVENTOS_NEGOCIO.ORCAMENTO_ENVIAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_ORDENS_SERVICO]: [
    EVENTOS_NEGOCIO.OS_CRIAR,
    EVENTOS_NEGOCIO.OS_CONSULTAR,
    EVENTOS_NEGOCIO.OS_INICIAR_DIAGNOSTICO,
    EVENTOS_NEGOCIO.OS_INICIAR_EXECUCAO,
  ],
  [PERMISSOES_INTERFACE.MANAGE_VENDAS]: [
    EVENTOS_NEGOCIO.VENDA_CONSULTAR,
    EVENTOS_NEGOCIO.VENDA_GERAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_FINANCEIRO]: [
    EVENTOS_NEGOCIO.PAGAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.PAGAMENTO_REGISTRAR,
    EVENTOS_NEGOCIO.LIVRO_CAIXA_CONSULTAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_CONSULTAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_GARANTIAS]: [
    EVENTOS_NEGOCIO.GARANTIA_ABRIR,
    EVENTOS_NEGOCIO.GARANTIA_CONSULTAR,
    EVENTOS_NEGOCIO.GARANTIA_ENVIAR_FORNECEDOR,
    EVENTOS_NEGOCIO.GARANTIA_REGISTRAR_RETORNO,
  ],
  [PERMISSOES_INTERFACE.MANAGE_COMPRAS]: [
    EVENTOS_NEGOCIO.FORNECEDOR_CONSULTAR,
    EVENTOS_NEGOCIO.FORNECEDOR_GERENCIAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_CONSULTAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_GERENCIAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_CATALOGO]: [
    EVENTOS_NEGOCIO.CATALOGO_CONSULTAR,
    EVENTOS_NEGOCIO.CATALOGO_GERENCIAR,
    EVENTOS_NEGOCIO.ESTOQUE_CONSULTAR,
  ],
  [PERMISSOES_INTERFACE.MANAGE_COMUNICACAO]: [
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
    EVENTOS_NEGOCIO.COMUNICACAO_TEMPLATE_GERENCIAR,
    EVENTOS_NEGOCIO.CONSULTA_IMEI_CONSULTAR,
  ],
};

export const MATRIZ_PERMISSOES: Record<PerfilSistema, ReadonlySet<EventoNegocio>> = {
  [PERFIS_SISTEMA.ADMINISTRADOR]: new Set(Object.values(EVENTOS_NEGOCIO)),
  [PERFIS_SISTEMA.ADMIN_EMPRESA]: new Set(Object.values(EVENTOS_NEGOCIO).filter(
    (evento) => evento !== EVENTOS_NEGOCIO.EMPRESA_GERENCIAR,
  )),
  [PERFIS_SISTEMA.GERENTE]: new Set(Object.values(EVENTOS_NEGOCIO).filter(
    (evento) => evento !== EVENTOS_NEGOCIO.NOTA_FISCAL_CANCELAR
      && evento !== EVENTOS_NEGOCIO.AUDITORIA_GERENCIAR
      && evento !== EVENTOS_NEGOCIO.USUARIO_GERENCIAR
      && evento !== EVENTOS_NEGOCIO.EMPRESA_GERENCIAR,
  )),
  [PERFIS_SISTEMA.ATENDENTE]: new Set([
    EVENTOS_NEGOCIO.RECEBIMENTO_CRIAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_EDITAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_GERAR_TERMO,
    EVENTOS_NEGOCIO.CLIENTE_CONSULTAR,
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
    EVENTOS_NEGOCIO.CATALOGO_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CRIAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_EDITAR_RASCUNHO,
    EVENTOS_NEGOCIO.ORCAMENTO_ENVIAR,
    EVENTOS_NEGOCIO.ORCAMENTO_REPROVAR,
    EVENTOS_NEGOCIO.OS_CRIAR,
    EVENTOS_NEGOCIO.OS_CONSULTAR,
    EVENTOS_NEGOCIO.OS_RESERVAR_PECA,
    EVENTOS_NEGOCIO.GARANTIA_ABRIR,
    EVENTOS_NEGOCIO.GARANTIA_CONSULTAR,
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
    EVENTOS_NEGOCIO.CONSULTA_IMEI_CONSULTAR,
    EVENTOS_NEGOCIO.CONSULTA_IMEI_GERENCIAR,
  ]),
  [PERFIS_SISTEMA.VENDAS]: new Set([
    EVENTOS_NEGOCIO.CLIENTE_CONSULTAR,
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
    EVENTOS_NEGOCIO.CATALOGO_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CRIAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_EDITAR_RASCUNHO,
    EVENTOS_NEGOCIO.ORCAMENTO_ENVIAR,
    EVENTOS_NEGOCIO.VENDA_CONSULTAR,
    EVENTOS_NEGOCIO.VENDA_GERAR,
  ]),
  [PERFIS_SISTEMA.RECEBIMENTO]: new Set([
    EVENTOS_NEGOCIO.RECEBIMENTO_CRIAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_EDITAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_GERAR_TERMO,
    EVENTOS_NEGOCIO.CLIENTE_CONSULTAR,
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
    EVENTOS_NEGOCIO.CATALOGO_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CRIAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
    EVENTOS_NEGOCIO.CONSULTA_IMEI_CONSULTAR,
  ]),
  [PERFIS_SISTEMA.TECNICO]: new Set([
    EVENTOS_NEGOCIO.RECEBIMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.CLIENTE_CONSULTAR,
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
    EVENTOS_NEGOCIO.CATALOGO_CONSULTAR,
    EVENTOS_NEGOCIO.ESTOQUE_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.OS_CRIAR,
    EVENTOS_NEGOCIO.OS_CONSULTAR,
    EVENTOS_NEGOCIO.OS_INICIAR_DIAGNOSTICO,
    EVENTOS_NEGOCIO.OS_AGUARDAR_PECA,
    EVENTOS_NEGOCIO.OS_RESERVAR_PECA,
    EVENTOS_NEGOCIO.OS_INICIAR_EXECUCAO,
    EVENTOS_NEGOCIO.OS_CONSUMIR_PECA,
    EVENTOS_NEGOCIO.OS_FINALIZAR,
    EVENTOS_NEGOCIO.GARANTIA_CONSULTAR,
    EVENTOS_NEGOCIO.GARANTIA_REGISTRAR_RETORNO,
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
    EVENTOS_NEGOCIO.CONSULTA_IMEI_CONSULTAR,
  ]),
  [PERFIS_SISTEMA.ESTOQUISTA]: new Set([
    EVENTOS_NEGOCIO.RECEBIMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.OS_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.CATALOGO_CONSULTAR,
    EVENTOS_NEGOCIO.CATALOGO_GERENCIAR,
    EVENTOS_NEGOCIO.ESTOQUE_CONSULTAR,
    EVENTOS_NEGOCIO.ESTOQUE_ENTRADA,
    EVENTOS_NEGOCIO.ESTOQUE_RESERVAR,
    EVENTOS_NEGOCIO.ESTOQUE_BAIXAR,
    EVENTOS_NEGOCIO.ESTOQUE_AJUSTAR,
    EVENTOS_NEGOCIO.ESTOQUE_ESTORNAR,
    EVENTOS_NEGOCIO.FORNECEDOR_CONSULTAR,
    EVENTOS_NEGOCIO.FORNECEDOR_GERENCIAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_CONSULTAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_GERENCIAR,
    EVENTOS_NEGOCIO.GARANTIA_CONSULTAR,
    EVENTOS_NEGOCIO.GARANTIA_ENVIAR_FORNECEDOR,
  ]),
  [PERFIS_SISTEMA.FINANCEIRO]: new Set([
    EVENTOS_NEGOCIO.CLIENTE_CONSULTAR,
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
    EVENTOS_NEGOCIO.CATALOGO_CONSULTAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.OS_CONSULTAR,
    EVENTOS_NEGOCIO.FORNECEDOR_CONSULTAR,
    EVENTOS_NEGOCIO.FORNECEDOR_GERENCIAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_CONSULTAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_GERENCIAR,
    EVENTOS_NEGOCIO.ESTOQUE_CONSULTAR,
    EVENTOS_NEGOCIO.VENDA_CONSULTAR,
    EVENTOS_NEGOCIO.VENDA_GERAR,
    EVENTOS_NEGOCIO.VENDA_CANCELAR,
    EVENTOS_NEGOCIO.PAGAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.PAGAMENTO_REGISTRAR,
    EVENTOS_NEGOCIO.PAGAMENTO_ESTORNAR,
    EVENTOS_NEGOCIO.NOTA_FISCAL_CONSULTAR,
    EVENTOS_NEGOCIO.LIVRO_CAIXA_CONSULTAR,
    EVENTOS_NEGOCIO.CONTA_FINANCEIRA_CONSULTAR,
    EVENTOS_NEGOCIO.CONTA_FINANCEIRA_GERENCIAR,
    EVENTOS_NEGOCIO.CATEGORIA_FINANCEIRA_CONSULTAR,
    EVENTOS_NEGOCIO.CATEGORIA_FINANCEIRA_GERENCIAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_CONSULTAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_GERENCIAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_BAIXAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_ESTORNAR,
    EVENTOS_NEGOCIO.MOVIMENTO_CAIXA_REGISTRAR,
    EVENTOS_NEGOCIO.MOVIMENTO_CAIXA_ESTORNAR,
    EVENTOS_NEGOCIO.RECORRENCIA_FINANCEIRA_CONSULTAR,
    EVENTOS_NEGOCIO.RECORRENCIA_FINANCEIRA_GERENCIAR,
    EVENTOS_NEGOCIO.RECORRENCIA_FINANCEIRA_PROCESSAR,
    EVENTOS_NEGOCIO.PROLABORE_REGISTRAR,
    EVENTOS_NEGOCIO.FECHAMENTO_MENSAL_GERENCIAR,
    EVENTOS_NEGOCIO.RELATORIO_FINANCEIRO_GERAR,
    EVENTOS_NEGOCIO.ANEXO_FINANCEIRO_CONSULTAR,
    EVENTOS_NEGOCIO.ANEXO_FINANCEIRO_GERENCIAR,
    EVENTOS_NEGOCIO.GARANTIA_CONSULTAR,
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
  ]),
  [PERFIS_SISTEMA.GARANTIAS]: new Set([
    EVENTOS_NEGOCIO.CLIENTE_CONSULTAR,
    EVENTOS_NEGOCIO.OS_CONSULTAR,
    EVENTOS_NEGOCIO.GARANTIA_ABRIR,
    EVENTOS_NEGOCIO.GARANTIA_CONSULTAR,
    EVENTOS_NEGOCIO.GARANTIA_ENVIAR_FORNECEDOR,
    EVENTOS_NEGOCIO.GARANTIA_REGISTRAR_RETORNO,
    EVENTOS_NEGOCIO.GARANTIA_FINALIZAR,
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
  ]),
  [PERFIS_SISTEMA.FISCAL]: new Set([
    EVENTOS_NEGOCIO.VENDA_CONSULTAR,
    EVENTOS_NEGOCIO.NOTA_FISCAL_CONSULTAR,
    EVENTOS_NEGOCIO.NOTA_FISCAL_EMITIR,
    EVENTOS_NEGOCIO.NOTA_FISCAL_CANCELAR,
  ]),
};

export function normalizarPerfil(perfil: string): PerfilSistema | null {
  const normalized = perfil.trim().toLowerCase();
  const aliases: Record<string, PerfilSistema> = {
    admin: PERFIS_SISTEMA.ADMINISTRADOR,
    administrador: PERFIS_SISTEMA.ADMINISTRADOR,
    admin_empresa: PERFIS_SISTEMA.ADMIN_EMPRESA,
    gerente: PERFIS_SISTEMA.GERENTE,
    atendente: PERFIS_SISTEMA.ATENDENTE,
    vendedor: PERFIS_SISTEMA.VENDAS,
    vendas: PERFIS_SISTEMA.VENDAS,
    recebimento: PERFIS_SISTEMA.RECEBIMENTO,
    tecnico: PERFIS_SISTEMA.TECNICO,
    tecnico_assistencia: PERFIS_SISTEMA.TECNICO,
    estoquista: PERFIS_SISTEMA.ESTOQUISTA,
    caixa: PERFIS_SISTEMA.FINANCEIRO,
    caixa_financeiro: PERFIS_SISTEMA.FINANCEIRO,
    financeiro: PERFIS_SISTEMA.FINANCEIRO,
    financas: PERFIS_SISTEMA.FINANCEIRO,
    garantias: PERFIS_SISTEMA.GARANTIAS,
    fiscal: PERFIS_SISTEMA.FISCAL,
  };

  return aliases[normalized] ?? null;
}

export function perfilPodeExecutarEvento(perfil: string, evento: EventoNegocio): boolean {
  const perfilNormalizado = normalizarPerfil(perfil);
  if (!perfilNormalizado) {
    return false;
  }

  return MATRIZ_PERMISSOES[perfilNormalizado].has(evento);
}

export function listarEventosPermitidos(perfil: string): EventoNegocio[] {
  const perfilNormalizado = normalizarPerfil(perfil);
  if (!perfilNormalizado) {
    return [];
  }

  return Array.from(MATRIZ_PERMISSOES[perfilNormalizado]);
}

export function listarPermissoesInterfacePermitidas(perfil: string): PermissaoInterface[] {
  const eventosPermitidos = new Set(listarEventosPermitidos(perfil));

  return Object.entries(EVENTOS_POR_PERMISSAO_INTERFACE)
    .filter(([, eventos]) => eventos.some((evento) => eventosPermitidos.has(evento)))
    .map(([permissao]) => permissao as PermissaoInterface);
}

export function serializarMatrizPermissoes() {
  return {
    perfis: Object.values(PERFIS_SISTEMA),
    eventos: EVENTOS_NEGOCIO,
    permissoesInterface: PERMISSOES_INTERFACE,
    eventosPorPermissaoInterface: EVENTOS_POR_PERMISSAO_INTERFACE,
    matriz: Object.fromEntries(
      Object.values(PERFIS_SISTEMA).map((perfil) => [
        perfil,
        {
          eventos: listarEventosPermitidos(perfil),
          permissoesInterface: listarPermissoesInterfacePermitidas(perfil),
        },
      ]),
    ),
  };
}
