export const PERFIS_SISTEMA = {
  ADMINISTRADOR: 'administrador',
  GERENTE: 'gerente',
  ATENDENTE: 'atendente',
  TECNICO: 'tecnico',
  ESTOQUISTA: 'estoquista',
  FINANCEIRO: 'financeiro',
  FISCAL: 'fiscal',
} as const;

export type PerfilSistema = (typeof PERFIS_SISTEMA)[keyof typeof PERFIS_SISTEMA];

export const EVENTOS_NEGOCIO = {
  EMPRESA_CONSULTAR: 'empresa.consultar',
  EMPRESA_GERENCIAR: 'empresa.gerenciar',
  USUARIO_CONSULTAR: 'usuario.consultar',
  USUARIO_GERENCIAR: 'usuario.gerenciar',

  RECEBIMENTO_CRIAR: 'recebimento.criar',
  RECEBIMENTO_GERAR_TERMO: 'recebimento.gerar_termo',

  CLIENTE_CRIAR: 'cliente.criar',
  CLIENTE_EDITAR: 'cliente.editar',
  CLIENTE_REMOVER: 'cliente.remover',

  ORCAMENTO_CRIAR: 'orcamento.criar',
  ORCAMENTO_EDITAR_RASCUNHO: 'orcamento.editar_rascunho',
  ORCAMENTO_ENVIAR: 'orcamento.enviar',
  ORCAMENTO_APROVAR: 'orcamento.aprovar',
  ORCAMENTO_REPROVAR: 'orcamento.reprovar',
  ORCAMENTO_CANCELAR: 'orcamento.cancelar',

  OS_CRIAR: 'os.criar',
  OS_INICIAR_DIAGNOSTICO: 'os.iniciar_diagnostico',
  OS_AGUARDAR_PECA: 'os.aguardar_peca',
  OS_RESERVAR_PECA: 'os.reservar_peca',
  OS_INICIAR_EXECUCAO: 'os.iniciar_execucao',
  OS_CONSUMIR_PECA: 'os.consumir_peca',
  OS_FINALIZAR: 'os.finalizar',
  OS_CANCELAR: 'os.cancelar',

  ESTOQUE_ENTRADA: 'estoque.entrada',
  ESTOQUE_RESERVAR: 'estoque.reservar',
  ESTOQUE_BAIXAR: 'estoque.baixar',
  ESTOQUE_AJUSTAR: 'estoque.ajustar',
  ESTOQUE_ESTORNAR: 'estoque.estornar',

  FORNECEDOR_CONSULTAR: 'fornecedor.consultar',
  FORNECEDOR_GERENCIAR: 'fornecedor.gerenciar',
  COMPRA_PEDIDO_CONSULTAR: 'compra_pedido.consultar',
  COMPRA_PEDIDO_GERENCIAR: 'compra_pedido.gerenciar',

  VENDA_CONSULTAR: 'venda.consultar',
  VENDA_GERAR: 'venda.gerar',
  VENDA_CANCELAR: 'venda.cancelar',
  PAGAMENTO_CONSULTAR: 'pagamento.consultar',
  PAGAMENTO_REGISTRAR: 'pagamento.registrar',
  PAGAMENTO_ESTORNAR: 'pagamento.estornar',

  LIVRO_CAIXA_CONSULTAR: 'livro_caixa.consultar',
  CONTA_FINANCEIRA_CONSULTAR: 'conta_financeira.consultar',
  CONTA_FINANCEIRA_GERENCIAR: 'conta_financeira.gerenciar',
  CATEGORIA_FINANCEIRA_CONSULTAR: 'categoria_financeira.consultar',
  CATEGORIA_FINANCEIRA_GERENCIAR: 'categoria_financeira.gerenciar',
  TITULO_FINANCEIRO_CONSULTAR: 'titulo_financeiro.consultar',
  TITULO_FINANCEIRO_GERENCIAR: 'titulo_financeiro.gerenciar',
  TITULO_FINANCEIRO_BAIXAR: 'titulo_financeiro.baixar',
  TITULO_FINANCEIRO_ESTORNAR: 'titulo_financeiro.estornar',
  MOVIMENTO_CAIXA_REGISTRAR: 'movimento_caixa.registrar',
  MOVIMENTO_CAIXA_ESTORNAR: 'movimento_caixa.estornar',
  RECORRENCIA_FINANCEIRA_CONSULTAR: 'recorrencia_financeira.consultar',
  RECORRENCIA_FINANCEIRA_GERENCIAR: 'recorrencia_financeira.gerenciar',
  RECORRENCIA_FINANCEIRA_PROCESSAR: 'recorrencia_financeira.processar',
  PROLABORE_REGISTRAR: 'prolabore.registrar',
  FECHAMENTO_MENSAL_GERENCIAR: 'fechamento_mensal.gerenciar',
  RELATORIO_FINANCEIRO_GERAR: 'relatorio_financeiro.gerar',
  ANEXO_FINANCEIRO_CONSULTAR: 'anexo_financeiro.consultar',
  ANEXO_FINANCEIRO_GERENCIAR: 'anexo_financeiro.gerenciar',

  NOTA_FISCAL_CONSULTAR: 'nota_fiscal.consultar',
  NOTA_FISCAL_EMITIR: 'nota_fiscal.emitir',
  NOTA_FISCAL_CANCELAR: 'nota_fiscal.cancelar',

  GARANTIA_ABRIR: 'garantia.abrir',
  GARANTIA_ENVIAR_FORNECEDOR: 'garantia.enviar_fornecedor',
  GARANTIA_REGISTRAR_RETORNO: 'garantia.registrar_retorno',
  GARANTIA_FINALIZAR: 'garantia.finalizar',

  NOTIFICACAO_ENVIAR: 'notificacao.enviar',
  COMUNICACAO_TEMPLATE_GERENCIAR: 'comunicacao_template.gerenciar',

  AUDITORIA_CONSULTAR: 'auditoria.consultar',
  AUDITORIA_GERENCIAR: 'auditoria.gerenciar',
} as const;

export type EventoNegocio = (typeof EVENTOS_NEGOCIO)[keyof typeof EVENTOS_NEGOCIO];

export const MATRIZ_PERMISSOES: Record<PerfilSistema, ReadonlySet<EventoNegocio>> = {
  [PERFIS_SISTEMA.ADMINISTRADOR]: new Set(Object.values(EVENTOS_NEGOCIO)),
  [PERFIS_SISTEMA.GERENTE]: new Set(Object.values(EVENTOS_NEGOCIO).filter(
    (evento) => evento !== EVENTOS_NEGOCIO.NOTA_FISCAL_CANCELAR
      && evento !== EVENTOS_NEGOCIO.AUDITORIA_GERENCIAR
      && evento !== EVENTOS_NEGOCIO.USUARIO_GERENCIAR,
  )),
  [PERFIS_SISTEMA.ATENDENTE]: new Set([
    EVENTOS_NEGOCIO.RECEBIMENTO_CRIAR,
    EVENTOS_NEGOCIO.RECEBIMENTO_GERAR_TERMO,
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
    EVENTOS_NEGOCIO.ORCAMENTO_CRIAR,
    EVENTOS_NEGOCIO.ORCAMENTO_EDITAR_RASCUNHO,
    EVENTOS_NEGOCIO.ORCAMENTO_ENVIAR,
    EVENTOS_NEGOCIO.ORCAMENTO_REPROVAR,
    EVENTOS_NEGOCIO.OS_CRIAR,
    EVENTOS_NEGOCIO.OS_RESERVAR_PECA,
    EVENTOS_NEGOCIO.GARANTIA_ABRIR,
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
  ]),
  [PERFIS_SISTEMA.TECNICO]: new Set([
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
    EVENTOS_NEGOCIO.OS_CRIAR,
    EVENTOS_NEGOCIO.OS_INICIAR_DIAGNOSTICO,
    EVENTOS_NEGOCIO.OS_AGUARDAR_PECA,
    EVENTOS_NEGOCIO.OS_RESERVAR_PECA,
    EVENTOS_NEGOCIO.OS_INICIAR_EXECUCAO,
    EVENTOS_NEGOCIO.OS_CONSUMIR_PECA,
    EVENTOS_NEGOCIO.OS_FINALIZAR,
    EVENTOS_NEGOCIO.GARANTIA_REGISTRAR_RETORNO,
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
  ]),
  [PERFIS_SISTEMA.ESTOQUISTA]: new Set([
    EVENTOS_NEGOCIO.ESTOQUE_ENTRADA,
    EVENTOS_NEGOCIO.ESTOQUE_RESERVAR,
    EVENTOS_NEGOCIO.ESTOQUE_BAIXAR,
    EVENTOS_NEGOCIO.ESTOQUE_AJUSTAR,
    EVENTOS_NEGOCIO.ESTOQUE_ESTORNAR,
    EVENTOS_NEGOCIO.FORNECEDOR_CONSULTAR,
    EVENTOS_NEGOCIO.FORNECEDOR_GERENCIAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_CONSULTAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_GERENCIAR,
    EVENTOS_NEGOCIO.GARANTIA_ENVIAR_FORNECEDOR,
  ]),
  [PERFIS_SISTEMA.FINANCEIRO]: new Set([
    EVENTOS_NEGOCIO.CLIENTE_CRIAR,
    EVENTOS_NEGOCIO.CLIENTE_EDITAR,
    EVENTOS_NEGOCIO.FORNECEDOR_CONSULTAR,
    EVENTOS_NEGOCIO.FORNECEDOR_GERENCIAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_CONSULTAR,
    EVENTOS_NEGOCIO.COMPRA_PEDIDO_GERENCIAR,
    EVENTOS_NEGOCIO.VENDA_CONSULTAR,
    EVENTOS_NEGOCIO.VENDA_GERAR,
    EVENTOS_NEGOCIO.VENDA_CANCELAR,
    EVENTOS_NEGOCIO.PAGAMENTO_CONSULTAR,
    EVENTOS_NEGOCIO.PAGAMENTO_REGISTRAR,
    EVENTOS_NEGOCIO.PAGAMENTO_ESTORNAR,
    EVENTOS_NEGOCIO.NOTA_FISCAL_CONSULTAR,
    EVENTOS_NEGOCIO.LIVRO_CAIXA_CONSULTAR,
    EVENTOS_NEGOCIO.CONTA_FINANCEIRA_CONSULTAR,
    EVENTOS_NEGOCIO.CONTA_FINANCEIRA_GERENCIAR,
    EVENTOS_NEGOCIO.CATEGORIA_FINANCEIRA_CONSULTAR,
    EVENTOS_NEGOCIO.CATEGORIA_FINANCEIRA_GERENCIAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_CONSULTAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_GERENCIAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_BAIXAR,
    EVENTOS_NEGOCIO.TITULO_FINANCEIRO_ESTORNAR,
    EVENTOS_NEGOCIO.MOVIMENTO_CAIXA_REGISTRAR,
    EVENTOS_NEGOCIO.MOVIMENTO_CAIXA_ESTORNAR,
    EVENTOS_NEGOCIO.RECORRENCIA_FINANCEIRA_CONSULTAR,
    EVENTOS_NEGOCIO.RECORRENCIA_FINANCEIRA_GERENCIAR,
    EVENTOS_NEGOCIO.RECORRENCIA_FINANCEIRA_PROCESSAR,
    EVENTOS_NEGOCIO.PROLABORE_REGISTRAR,
    EVENTOS_NEGOCIO.FECHAMENTO_MENSAL_GERENCIAR,
    EVENTOS_NEGOCIO.RELATORIO_FINANCEIRO_GERAR,
    EVENTOS_NEGOCIO.ANEXO_FINANCEIRO_CONSULTAR,
    EVENTOS_NEGOCIO.ANEXO_FINANCEIRO_GERENCIAR,
    EVENTOS_NEGOCIO.NOTIFICACAO_ENVIAR,
  ]),
  [PERFIS_SISTEMA.FISCAL]: new Set([
    EVENTOS_NEGOCIO.VENDA_CONSULTAR,
    EVENTOS_NEGOCIO.NOTA_FISCAL_CONSULTAR,
    EVENTOS_NEGOCIO.NOTA_FISCAL_EMITIR,
    EVENTOS_NEGOCIO.NOTA_FISCAL_CANCELAR,
  ]),
};

export function normalizarPerfil(perfil: string): PerfilSistema | null {
  const normalized = perfil.trim().toLowerCase();
  const aliases: Record<string, PerfilSistema> = {
    admin: PERFIS_SISTEMA.ADMINISTRADOR,
    administrador: PERFIS_SISTEMA.ADMINISTRADOR,
    gerente: PERFIS_SISTEMA.GERENTE,
    atendente: PERFIS_SISTEMA.ATENDENTE,
    tecnico: PERFIS_SISTEMA.TECNICO,
    tecnico_assistencia: PERFIS_SISTEMA.TECNICO,
    estoquista: PERFIS_SISTEMA.ESTOQUISTA,
    caixa: PERFIS_SISTEMA.FINANCEIRO,
    caixa_financeiro: PERFIS_SISTEMA.FINANCEIRO,
    financeiro: PERFIS_SISTEMA.FINANCEIRO,
    financas: PERFIS_SISTEMA.FINANCEIRO,
    fiscal: PERFIS_SISTEMA.FISCAL,
  };

  return aliases[normalized] ?? null;
}

export function perfilPodeExecutarEvento(perfil: string, evento: EventoNegocio): boolean {
  const perfilNormalizado = normalizarPerfil(perfil);
  if (!perfilNormalizado) {
    return false;
  }

  return MATRIZ_PERMISSOES[perfilNormalizado].has(evento);
}

export function listarEventosPermitidos(perfil: string): EventoNegocio[] {
  const perfilNormalizado = normalizarPerfil(perfil);
  if (!perfilNormalizado) {
    return [];
  }

  return Array.from(MATRIZ_PERMISSOES[perfilNormalizado]);
}
