import { Types } from 'mongoose';
import { CreateLogEventoDto } from './dto/create-log-evento.dto';

export const AUDITORIA_EVENTOS = {
  RECEBIMENTO_CRIADO: 'RECEBIMENTO_CRIADO',
  TERMO_GERADO: 'TERMO_GERADO',
  CLIENTE_CRIADO: 'CLIENTE_CRIADO',
  CLIENTE_ATUALIZADO: 'CLIENTE_ATUALIZADO',
  CLIENTE_REMOVIDO: 'CLIENTE_REMOVIDO',
  ORCAMENTO_CRIADO: 'ORCAMENTO_CRIADO',
  ORCAMENTO_ENVIADO: 'ORCAMENTO_ENVIADO',
  ORCAMENTO_APROVADO: 'ORCAMENTO_APROVADO',
  ORCAMENTO_REPROVADO: 'ORCAMENTO_REPROVADO',
  ORCAMENTO_CANCELADO: 'ORCAMENTO_CANCELADO',
  OS_CRIADA: 'OS_CRIADA',
  OS_STATUS_ALTERADO: 'OS_STATUS_ALTERADO',
  PECA_RESERVADA: 'PECA_RESERVADA',
  PECA_CONSUMIDA: 'PECA_CONSUMIDA',
  ESTOQUE_AJUSTADO: 'ESTOQUE_AJUSTADO',
  FORNECEDOR_CRIADO: 'FORNECEDOR_CRIADO',
  FORNECEDOR_ATUALIZADO: 'FORNECEDOR_ATUALIZADO',
  FORNECEDOR_REMOVIDO: 'FORNECEDOR_REMOVIDO',
  PEDIDO_COMPRA_CRIADO: 'PEDIDO_COMPRA_CRIADO',
  PEDIDO_COMPRA_ATUALIZADO: 'PEDIDO_COMPRA_ATUALIZADO',
  PEDIDO_COMPRA_REMOVIDO: 'PEDIDO_COMPRA_REMOVIDO',
  ITEM_PEDIDO_COMPRA_CRIADO: 'ITEM_PEDIDO_COMPRA_CRIADO',
  ITEM_PEDIDO_COMPRA_ATUALIZADO: 'ITEM_PEDIDO_COMPRA_ATUALIZADO',
  ITEM_PEDIDO_COMPRA_REMOVIDO: 'ITEM_PEDIDO_COMPRA_REMOVIDO',
  VENDA_GERADA: 'VENDA_GERADA',
  VENDA_ATUALIZADA: 'VENDA_ATUALIZADA',
  VENDA_REMOVIDA: 'VENDA_REMOVIDA',
  PAGAMENTO_REGISTRADO: 'PAGAMENTO_REGISTRADO',
  PAGAMENTO_ATUALIZADO: 'PAGAMENTO_ATUALIZADO',
  PAGAMENTO_REMOVIDO: 'PAGAMENTO_REMOVIDO',
  CONTA_FINANCEIRA_CRIADA: 'CONTA_FINANCEIRA_CRIADA',
  CONTA_FINANCEIRA_ATUALIZADA: 'CONTA_FINANCEIRA_ATUALIZADA',
  CONTA_FINANCEIRA_REMOVIDA: 'CONTA_FINANCEIRA_REMOVIDA',
  CATEGORIA_FINANCEIRA_CRIADA: 'CATEGORIA_FINANCEIRA_CRIADA',
  CATEGORIA_FINANCEIRA_ATUALIZADA: 'CATEGORIA_FINANCEIRA_ATUALIZADA',
  CATEGORIA_FINANCEIRA_REMOVIDA: 'CATEGORIA_FINANCEIRA_REMOVIDA',
  TITULO_FINANCEIRO_CRIADO: 'TITULO_FINANCEIRO_CRIADO',
  TITULO_FINANCEIRO_ATUALIZADO: 'TITULO_FINANCEIRO_ATUALIZADO',
  TITULO_FINANCEIRO_CANCELADO: 'TITULO_FINANCEIRO_CANCELADO',
  TITULO_FINANCEIRO_BAIXADO: 'TITULO_FINANCEIRO_BAIXADO',
  TITULO_FINANCEIRO_ESTORNADO: 'TITULO_FINANCEIRO_ESTORNADO',
  MOVIMENTO_CAIXA_REGISTRADO: 'MOVIMENTO_CAIXA_REGISTRADO',
  MOVIMENTO_CAIXA_ESTORNADO: 'MOVIMENTO_CAIXA_ESTORNADO',
  RECORRENCIA_FINANCEIRA_CRIADA: 'RECORRENCIA_FINANCEIRA_CRIADA',
  RECORRENCIA_FINANCEIRA_ATUALIZADA: 'RECORRENCIA_FINANCEIRA_ATUALIZADA',
  RECORRENCIA_FINANCEIRA_REMOVIDA: 'RECORRENCIA_FINANCEIRA_REMOVIDA',
  RECORRENCIA_FINANCEIRA_PROCESSADA: 'RECORRENCIA_FINANCEIRA_PROCESSADA',
  PROLABORE_REGISTRADO: 'PROLABORE_REGISTRADO',
  FECHAMENTO_MENSAL_FECHADO: 'FECHAMENTO_MENSAL_FECHADO',
  FECHAMENTO_MENSAL_REABERTO: 'FECHAMENTO_MENSAL_REABERTO',
  NOTA_FISCAL_EMITIDA: 'NOTA_FISCAL_EMITIDA',
  NOTA_FISCAL_ATUALIZADA: 'NOTA_FISCAL_ATUALIZADA',
  NOTA_FISCAL_REMOVIDA: 'NOTA_FISCAL_REMOVIDA',
  GARANTIA_ABERTA: 'GARANTIA_ABERTA',
  GARANTIA_STATUS_ALTERADO: 'GARANTIA_STATUS_ALTERADO',
  GARANTIA_FINALIZADA: 'GARANTIA_FINALIZADA',
} as const;

export type AuditoriaEvento = (typeof AUDITORIA_EVENTOS)[keyof typeof AUDITORIA_EVENTOS];

export const AUDITORIA_ENTIDADES = {
  RECEBIMENTO: 'recebimento',
  TERMO_RECEBIMENTO: 'termo_recebimento',
  CLIENTE: 'cliente',
  ORCAMENTO: 'orcamento',
  ORDEM_SERVICO: 'ordem_servico',
  ESTOQUE: 'estoque',
  FORNECEDOR: 'fornecedor',
  PEDIDO_COMPRA: 'pedido_compra',
  ITEM_PEDIDO_COMPRA: 'item_pedido_compra',
  VENDA: 'venda',
  PAGAMENTO: 'pagamento',
  CONTA_FINANCEIRA: 'conta_financeira',
  CATEGORIA_FINANCEIRA: 'categoria_financeira',
  TITULO_FINANCEIRO: 'titulo_financeiro',
  MOVIMENTO_CAIXA: 'movimento_caixa',
  RECORRENCIA_FINANCEIRA: 'recorrencia_financeira',
  PROLABORE: 'prolabore',
  FECHAMENTO_MENSAL: 'fechamento_mensal',
  NOTA_FISCAL: 'nota_fiscal',
  GARANTIA: 'garantia',
} as const;

export type AuditoriaEntidade = (typeof AUDITORIA_ENTIDADES)[keyof typeof AUDITORIA_ENTIDADES];

export interface EventoNegocioAuditavel {
  empresaId: string | Types.ObjectId;
  usuarioId: string | Types.ObjectId;
  tipoEvento: AuditoriaEvento;
  entidade: AuditoriaEntidade;
  entidadeId: string | Types.ObjectId;
  dados?: Record<string, unknown>;
}

export function toObjectId(value: string | Types.ObjectId): Types.ObjectId {
  return value instanceof Types.ObjectId ? value : new Types.ObjectId(value);
}

export function montarLogEventoNegocio(evento: EventoNegocioAuditavel): CreateLogEventoDto {
  return {
    empresaId: toObjectId(evento.empresaId),
    usuarioId: toObjectId(evento.usuarioId),
    tipoEvento: evento.tipoEvento,
    entidade: evento.entidade,
    entidadeId: toObjectId(evento.entidadeId),
    dados: evento.dados ?? {},
  };
}
