name: Deploy Backend Nest

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build imagem
        run: docker build -t mantecsystems/mantec3-back:latest .

      - name: Push imagem
        run: docker push mantecsystems/mantec3-back:latest

      # 🔥 Deploy usando caminho absoluto no servidor
      - name: Deploy no Swarm (stack)
        run: |
          docker pull mantecsystems/mantec3-back:latest
          docker stack deploy -c /home/lemuel/stacks/05-apps/mantec3.yml mantec3